platform :ios, '10.0'

target 'flickr-images' do
    use_frameworks!
    pod 'Anchorage', '~> 4.3.1'
    pod 'Alamofire', '~> 4.8.2'
    pod 'AlamofireImage', '~> 3.5.2'
    pod 'SwiftyJSON', '~> 5.0.0'
end
